#facebook :
#  client :
#    clientId :
#    clientSecret:
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#    scope: email
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link
#
#google :
#  client :
#    clientId :
#    clientSecret:
#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    scope: email, profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
#
#
#naver :
#  client :
#    clientId :
#    clientSecret :
#    accessTokenUri : https://nid.naver.com/oauth2.0/token
#    userAuthorizationUri : https://nid.naver.com/oauth2.0/authorize
#    tokenName : oauth_token
#    authenticationScheme : query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri : https://openapi.naver.com/v1/nid/me

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa_ex?useSSL=false
    username: root
    password: jpa_user
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
          facebook:
            client-id: 
            client-secret: 

custom:
  oauth2:
    kakao:
      client-id: 
